config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :todolists
  resources :layouts
  root to:'layouts#top'

  resources :groups do
    get "join" =>"groups#join"
  end
  resources :users
  # get 'top' => 'homes#top'
  # get 'todolists/new'
  # post 'todolists' => 'todolists#create'
  # get 'todolists' => 'todolists#index'
  # get 'todolists/:id' => 'todolists#show',as: 'todolist'
  # get 'todolists/:id/edit' => 'todolists#edit',as: 'edit_todolist'
  # patch 'todolist/:id' => 'todolist#update',as: 'update_todolist'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image

  has_many :group_users
  has_many :users, through: :group_users
  # belongs_to :user

  # validates :name, presence: true
  # validates :introduction, presence: true

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/list.rb
class List < ApplicationRecord
  attachment :image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  has_many :lists
  has_many :group_users   #中間テーブル！
  has_many :groups, through: :group_users
  # has_many :owned_groups, class_name: "Group"
  # has_many :favorites, dependent: :destroy
  # has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :authenticate_user!
  # before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @list = List.new

    @groups = Group.all
  end

  def show
    @list = List.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    # @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)

      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
      redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :image, :introduction)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end




end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController



  def index
  end

  def show
  end

  def new
    # @listnew = List.new
  end

  def create
    # list = List.new(list_params)
    # list.save
    # redirect_to layouts_path
  end


  def edit

  end

  # private
  # def list_params
  #   params.require(:list).permit(:title,:body)
  # end


end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController


  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to todolists_path(list.id)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list)
  end


  private
  def list_params
    params.require(:list).permit(:title,:body,:image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.attachment_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= attachment_image_tag group, :image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td>
                <% if group.owner_id == current_user.id %>
                  <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%#= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%#= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <td><%= attachment_image_tag @group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg" %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <% if @group.owner_id == current_user.id %>
              <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>

              <%= link_to 'グループ削除',group_all_destroy_path(@group),method: :delete,data: { confirm: '本当に削除しますか？' } ,
              class: "btn btn-sm btn-outline-danger" %>



            <% end %>



          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>HTMLの復習</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
     <header class="shadow-sm">
       <nav class="navbar navbar-expand-lg navbar-light">
         <div class="container">
           <a class="navbar-brand" href="/">
             <img class="logo" src="/assets/img/logo.png" alt="ロゴ">
           </a>

      <!--ハンバーガーメニュー-->
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>

           <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                   <li class="nav-item">
                     <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                   </li>
                   <li class="nav-item">
                     <%= link_to '投稿フォーム', new_layout_path, class: 'nav-link text-dark' %>
                   </li>
                <li class="nav-item">
                  <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
                </li>
                   <li class="nav-item">

                      <%= link_to '投稿一覧', todolists_path, class: "nav-link text-dark" %>

                   </li>
               <% else %>
                   <li class="nav-item">
                     <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
                   </li>
                   <li class="nav-item">
                     <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                   </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
   </header>



    <%= yield %>

  </body>

  <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">

          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <script src="jquery.min.js"></script>
    <script src= "app.js"></script>
  </body>
</html>

app/views/layouts/top.html.erb
<div class="main-visual">
 <p class="main-visual-name">
  Lorem Ipsum
 </p>

 <p class="main-visual-text">
  simply dummy text of the printing
 </p>
</div>

app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model:@list, url:"/todolists/#{@list.id}", local:true do |f| %>
 <h4>タイトル</h4>
  <%= f.text_field:title %>
 <h4>本文</h4>
  <%= f.text_area:body %>
  <%= f.submit '保存' %>
<% end %>

app/views/todolists/index.html.erb
<h1>投稿一覧</h1>
<% @lists.each do |list| %>
<p>タイトル</p>
<span>
  <%= link_to list.title, todolist_path(list) %>
</span>
<p>画像</p>
<%= attachment_image_tag @list,:image,:fill, 100,100,format:'jpeg' %>
<% end %>

<div>
  <%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %>
</div>

app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!-- form_with部分 -->
<%= form_with model:@list,url:'/todolists' ,local:true do |f| %>


  <h4>タイトル</h4>
  <%= f.text_field :title %>



  <h4>本文</h4>
  <%= f.text_area :body %>

  <h4>画像</h4>
  <%= f.attachment_field :image %>


  <%= f.submit '投稿' %>

<% end %>

app/views/todolists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @list,:image,:fill,300,300,format:'jpeg' %>
<%= link_to "編集", edit_todolist_path(@list.id) %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
   <div class='row'>
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <!--サクセスメッセージ-->
      <p id="notice">
        <%= notice %>
      </p>

      <!--エラーメッセージ-->
      <div class="error">
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>

      <!--プロフィール編集フォーム-->
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Profile_Image %>
          <%= f.attachment_field :profile_image, placeholder: "Image",class:"form-control-file"%>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class:"btn btn-primary" %>
        </div>
      <% end %>


   </div> <!--col-sm-12-->
 </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
     <div class="col-md-3">

           <h1>User Info</h1>
             <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: '100x100' %>

           <table class="table">
             <tbody>
                <tr>
                  <th>name</th> <!--ユーザー名表示-->
                  <th><%= @user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th> <!--自己紹介文-->
                  <th><%= @user.introduction %></th>
                </tr>

        <!--<tr>-->
        <!--  <th>follows</th>-->
        <!--  <th><%#= link_to user.followings.count, user_followings_path(user.id) %></th>  <!--user_relationships_path かも-->
        <!--</tr>-->
        <!--<tr>-->
        <!--  <th>followers</th>-->
        <!--  <th><%#= link_to user.followers.count, user_followers_path(user.id) %></th>-->
        <!--</tr>-->
            </tbody>
         </table>

       <!--<div class="row">-->
       <!--     <%# if user != current_user %>-->
       <!--      <%#= render "relationships/info", user: user %>   <!--info.html.erb(フォローボタン)の呼び出し-->
       <!--     <%# else %>-->
       <!--      <%#= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>-->
       <!--     <%# end %>-->
       <!--</div>-->
    </div>
  </div>
</div> <!--container-->

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>